#!/usr/bin/env bash

# Background
#
# There are a few differences between the top command used by OS X
# and Linux. As a simple work-around, this script provides a simple but portable
# alternative for monitoring processes with a specified command name.

# Author: Karl Marklund <karl.marklund@it.uu.se>
#
# 2016-11-27: First version.

delay=1;

function usage {
    cat <<EOF
Usage: `basename $0` [-s delay] cmd

A top-like command that only lists USER, PID, STAT and COMM for the
current user and and proceses with a command name with a grep match of cmd.

Options:
 -s delay    Delay in seconds between refresh, default = $delay.
EOF
}

while getopts "h?:s:" opt;
do
    case "$opt" in
        h|\?) usage
              exit 0
              ;;
        s ) delay=$OPTARG
            echo "delay = $delay"
           ;;
    esac
done

shift $(($OPTIND - 1))

if [[ ! $1 ]] ; then
    usage
    exit
fi

while :;
do
    clear
    echo "Press Ctrl-C to exit"
    echo
    `dirname "$0"`/my-ps $1
    sleep $delay
done
