#!/usr/bin/env bash


function usage {
    cat <<EOF
Usage: my-ps [cmd]

A variation on the ps command that only lists USER, PID, STAT and COMM for the
current user. If the optional argument cmd is provided, only processes with
command name cmd are listed.
EOF

}

while getopts "h?:" opt;
do
    case "$opt" in
        h|\?) usage
              exit 0
              ;;
    esac
done

# Usage: my-ps [cmd]

cmd="ps -o user,pid,ppid,state,comm"

if [[ $1 ]] ; then
   $cmd | head -n1 && $cmd -u $USER | grep $1
else
    $cmd -u $USER
fi
